### ISSUE TITLE
How to use with BB9-E

### ISSUE THREAD

**Issue by H4xl0r** [EnotYoyo/pysphero#14]
Hey there,
Got an old BB9E... would like to use it with your py..

i got it to the point where find toy says : 

`root@kali:~/pysphero/examples# python3 find_toy.py 
Found ed:f9:98:69:43:0c
Traceback (most recent call last):
  File "find_toy.py", line 16, in <module>
    main()
  File "find_toy.py", line 10, in main
    sphero.power.wake()
  File "/usr/local/lib/python3.8/dist-packages/pysphero/device_api/power.py", line 76, in wake
    self.request(PowerCommand.wake)
  File "/usr/local/lib/python3.8/dist-packages/pysphero/device_api/device_api.py", line 27, in request
    return self.ble_adapter.write(
  File "/usr/local/lib/python3.8/dist-packages/pysphero/bluetooth/gatt_adapter.py", line 70, in write
    return self.packet_collector.get_response(packet, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pysphero/bluetooth/packet_collector.py", line 46, in get_response
    raise PySpheroTimeoutError(f"Timeout error for response of {packet}")
pysphero.exceptions.PySpheroTimeoutError: Timeout error for response of Packet(flg: 0x0a did: 0x13 cid: 0x0d seq: 0x01)
`

Has it something to do with the api_v2 = "00010002-574f-4f20-5370-6865726f2121" ?
How do i get those values if so ? 
Is the connection even ok ? 
do i have to be paired ? cause its just paired a few seconds ? 

would be cool if you could help a bit to get BB9-E to talk to me :-)

**Comment by H4xl0r** [comment]
@EnotYoyo

**Comment by EnotYoyo** [comment]
> Has it something to do with the api_v2 = "00010002-574f-4f20-5370-6865726f2121" ?
No, this api for all toys (see [this](https://github.com/igbopie/spherov2.j) library with support BB9)

Try using bluepy bluetooth stack: 
```python
from time import sleep

from pysphero.core import Sphero
from pysphero.bluetooth.bluepy_adapter import BluepyAdapter

def main():
    mac_address = "ed:f9:98:69:43:0c"
    with Sphero(mac_address=mac_address) as sphero:
        sphero.ble_adapter.close()
        sphero.ble_adapter = BluepyAdapter(mac_address)
        sphero.power.wake()
        sleep(2)
        sphero.power.enter_soft_sleep()

if __name__ == "__main__":
    main()
```

P.S.  I don't know, why BB9E don't respond.

**Comment by EnotYoyo** [comment]
The message was sent to the sphero, perhaps the problem is in the initialization. Can you [capture](https://www.nowsecure.com/blog/2014/02/07/bluetooth-packet-capture-on-android-4-4/) bluetooth packets, when connected to toy?

**Comment by H4xl0r** [comment]
Hey @EnotYoyo first thanks for the reply :-) 
I was playing also with some paramters but still no luck at all.
I can capture packs no problem tell me what u need , just the Bluetooth HCI snoop log ?

:-) if you got discord add me :  https://privnote.com/pbbqCSCq#B2oBI0JqC

**Comment by H4xl0r** [comment]
there you go 
[bb9e_sphero_edu_btsnoop_hci.zip](https://github.com/EnotYoyo/pysphero/files/4661871/bb9e_sphero_edu_btsnoop_hci.zip)

Was Running a Program with different commands : 

![Screenshot_2020-05-21-11-32-22](https://user-images.githubusercontent.com/31049432/82549453-3e6fce80-9b5d-11ea-82ec-651968d928c4.jpg)
![Screenshot_2020-05-21-11-32-17](https://user-images.githubusercontent.com/31049432/82549463-416abf00-9b5d-11ea-85ee-13d41465f2d3.jpg)

**Comment by EnotYoyo** [comment]
I'll try to look at it soon, thanks!

**Comment by EnotYoyo** [comment]
@H4xl0r Try this:
```python
from time import sleep

from pysphero.core import Sphero


def main():
    mac_address = "ed:f9:98:69:43:0c"
    with Sphero(mac_address=mac_address) as sphero:
        for service in sphero.ble_adapter._device.services:
            for characteristic in service.characteristics:
                if str(characteristic.uuid) == "00020005-574f-4f20-5370-6865726f2121":
                    anti_dos = characteristic
                    anti_dos.write_value(b"usetheforce...band")

        sphero.power.wake()
        sleep(2)
        sphero.power.enter_soft_sleep()


if __name__ == "__main__":
    main()

```

**Comment by H4xl0r** [comment]
First exectue :
`ubu@ubuntu:~/pysphero/examples$ python3 test2.py 
Traceback (most recent call last):
  File "test2.py", line 21, in <module>
    main()
  File "test2.py", line 8, in main
    with Sphero(mac_address=mac_address) as sphero:
  File "/usr/local/lib/python3.8/dist-packages/pysphero/core.py", line 42, in __enter__
    self.ble_adapter = BleAdapter(self.mac_address)
  File "/usr/local/lib/python3.8/dist-packages/pysphero/bluetooth/gatt_adapter.py", line 38, in __init__
    self.ch_api_v2 = self._find_api_v2()
  File "/usr/local/lib/python3.8/dist-packages/pysphero/bluetooth/gatt_adapter.py", line 51, in _find_api_v2
    raise PySpheroRuntimeError("Sphero v2 characteristic not found")
pysphero.exceptions.PySpheroRuntimeError: Sphero v2 characteristic not found
ubu@ubuntu:~/pysphero/examples$ 
`

second execute:
`ubu@ubuntu:~/pysphero/examples$ python3 test2.py 
Traceback (most recent call last):
  File "test2.py", line 21, in <module>
    main()
  File "test2.py", line 15, in main
    sphero.power.wake()
  File "/usr/local/lib/python3.8/dist-packages/pysphero/device_api/power.py", line 76, in wake
    self.request(PowerCommand.wake)
  File "/usr/local/lib/python3.8/dist-packages/pysphero/device_api/device_api.py", line 27, in request
    return self.ble_adapter.write(
  File "/usr/local/lib/python3.8/dist-packages/pysphero/bluetooth/gatt_adapter.py", line 70, in write
    return self.packet_collector.get_response(packet, timeout)
  File "/usr/local/lib/python3.8/dist-packages/pysphero/bluetooth/packet_collector.py", line 46, in get_response
    raise PySpheroTimeoutError(f"Timeout error for response of {packet}")
pysphero.exceptions.PySpheroTimeoutError: Timeout error for response of Packet(flg: 0x0a did: 0x13 cid: 0x0d seq: 0x01)
`

damn is something wrong with the bluetooth ? 
`ubu@ubuntu:~/pysphero/examples$ hciconfig 
hci0:	Type: Primary  Bus: USB
	BD Address: 00:1A:7D:DA:71:15  ACL MTU: 310:10  SCO MTU: 64:8
	UP RUNNING 
	RX bytes:13658 acl:62 sco:0 events:620 errors:0
	TX bytes:11021 acl:62 sco:0 commands:186 errors:0
`
even changed systems (fresh clean ubuntu).

**Comment by H4xl0r** [comment]
now whe know why he is evil .... :-)

**Comment by EnotYoyo** [comment]
Um.. The "usetheforce...band" line should work...
Try [this](https://github.com/EnotYoyo/pysphero/tree/%2314/bb9e-support) branch.

**Comment by H4xl0r** [comment]
Works (find toy makes him wake now ) 
YAY nice work mate !

**Comment by zzrs123** [comment]
Hello!
Do you know how to connect sphero bolt on ubuntu phsical machine(not vm) ?
My bluetooth can detect my bolt ( called SB-X0C6),but I can't connect it by bluetooth gui.
I try to run the code directly by change the mac address,but there still some errors:
For example, I run the wake.py in vscode, and I get:
Traceback (most recent call last):
File "/home/zzrs123/Pysphero/pysphero/examples/wake.py", line 15, in
main()
File "/home/zzrs123/Pysphero/pysphero/examples/wake.py", line 9, in main
sphero.power.wake()
File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/device_api/power.py", line 76, in wake
self.request(PowerCommand.wake)
File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/device_api/device_api.py", line 35, in request
return self.ble_adapter.write(
File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/bluetooth/gatt_adapter.py", line 76, in write
return self.packet_collector.get_response(packet, raise_api_error, timeout)
File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/bluetooth/packet_collector.py", line 53, in get_response
raise PySpheroTimeoutError(f"Timeout error for response of {packet}")
pysphero.exceptions.PySpheroTimeoutError: Timeout error for response of Packet(flg: 0x0a did: 0x13 cid: 0x0d seq: 0x01)
