### ISSUE TITLE
How to manipulate sensor data

### ISSUE THREAD

**Issue by Georacer** [EnotYoyo/pysphero#26]
Hello there!

Thanks a bunch for this package.

I have a question regarding sensors. I'm running your [example on sensors](https://github.com/EnotYoyo/pysphero/blob/fdac7f19c27e367919fda050502826834865edc0/examples/sensors.py) fine, but now I want to use the data packet in the rest of my code.

How can I get this data out of the callback function and pass it to other functions?
I'm very new to multithreading in Python, but I see that you do not provide the future object to get the result from.
Am I missing something?

Thanks in advance.

**Comment by zzrs123** [comment]
Hello!
Do you know how to connect sphero bolt on ubuntu phsical machine(not vm) ?
My bluetooth can detect my bolt ( called SB-X0C6),but I can't connect it by bluetooth gui.
I try to run the code directly by change the mac address,but there still some errors:
For example, I run the wake.py in vscode, and I get:
Traceback (most recent call last):
  File "/home/zzrs123/Pysphero/pysphero/examples/wake.py", line 15, in <module>
    main()
  File "/home/zzrs123/Pysphero/pysphero/examples/wake.py", line 9, in main
    sphero.power.wake()
  File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/device_api/power.py", line 76, in wake
    self.request(PowerCommand.wake)
  File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/device_api/device_api.py", line 35, in request
    return self.ble_adapter.write(
  File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/bluetooth/gatt_adapter.py", line 76, in write
    return self.packet_collector.get_response(packet, raise_api_error, timeout)
  File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/bluetooth/packet_collector.py", line 53, in get_response
    raise PySpheroTimeoutError(f"Timeout error for response of {packet}")
pysphero.exceptions.PySpheroTimeoutError: Timeout error for response of Packet(flg: 0x0a did: 0x13 cid: 0x0d seq: 0x01)

**Comment by KiikiTinna** [comment]
@zzrs123  did you solve this? I am also trying the same without success
