### ISSUE TITLE
Resetting Sphero Orientation

### ISSUE THREAD

**Issue by dirkmcpherson** [EnotYoyo/pysphero#27]
Hi, is it possible to reset the sphero's internal orientation once it's powered? It senses a Quaternion who's default 0 is whichever way the sphero is facing when its powered on. Is it possible to turn the sphero to a heading, and then reset its internal orientation representation to 0?

Thanks for the great work on this library.

**Comment by zzrs123** [comment]
Hello!
Do you know how to connect sphero bolt on ubuntu phsical machine(not vm) ?
My bluetooth can detect my bolt ( called SB-X0C6),but I can't connect it by bluetooth gui.
I try to run the code directly by change the mac address,but there still some errors:
For example, I run the wake.py in vscode, and I get:
Traceback (most recent call last):
File "/home/zzrs123/Pysphero/pysphero/examples/wake.py", line 15, in
main()
File "/home/zzrs123/Pysphero/pysphero/examples/wake.py", line 9, in main
sphero.power.wake()
File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/device_api/power.py", line 76, in wake
self.request(PowerCommand.wake)
File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/device_api/device_api.py", line 35, in request
return self.ble_adapter.write(
File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/bluetooth/gatt_adapter.py", line 76, in write
return self.packet_collector.get_response(packet, raise_api_error, timeout)
File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/bluetooth/packet_collector.py", line 53, in get_response
raise PySpheroTimeoutError(f"Timeout error for response of {packet}")
pysphero.exceptions.PySpheroTimeoutError: Timeout error for response of Packet(flg: 0x0a did: 0x13 cid: 0x0d seq: 0x01)
