### ISSUE TITLE
How to connect my bolt & start this project?

### ISSUE THREAD

**Issue by zzrs123** [EnotYoyo/pysphero#29]
I am running PySphero on an Ubuntu 20.04 LTS with Python 3.8.10
Maybe I 'm not good at programming on Ubuntu. I don't know how to connect my sphero bolt, because I can't find my device in my bluetooth list(gui on upper right corner).
Maybe I don't know how to start pysphero?
Here is my oprations:
1. install the vscode
2. try run code `core.py`、`wake.py`, but it doesn't work.
3. Traceback (most recent call last):
  File "/home/zzrs123/Pysphero/pysphero/examples_lmq/wake.py", line 22, in <module>
    main()
  File "/home/zzrs123/Pysphero/pysphero/examples_lmq/wake.py", line 10, in main
    with Sphero(mac_address=mac_address) as sphero:
  File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/core.py", line 49, in __enter__
    self._ble_adapter = self._ble_adapter_cls(self.mac_address)
  File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/bluetooth/gatt_adapter.py", line 39, in __init__
    ch_force_band = self._find_characteristic(SpheroCharacteristic.force_band.value)
  File "/home/zzrs123/.local/lib/python3.8/site-packages/pysphero/bluetooth/gatt_adapter.py", line 56, in _find_characteristic
    raise PySpheroRuntimeError(f"Characteristic {characteristic} not found")
pysphero.exceptions.PySpheroRuntimeError: Characteristic 00020005-574f-4f20-5370-6865726f2121 not found

**Comment by zzrs123** [comment]
One of closed issues looks similar to my question,but i can't solve my problem with it.
Thanks again!
