### ISSUE TITLE
Timeout error for response of Packet

### ISSUE THREAD

**Issue by STRATOS-ROBOTICS** [EnotYoyo/pysphero#8]
Hello i tried your python program and it is very well but i had an error. it is about the time response of the packet; maybe you have also this issue and if not,  how i can resolve this please?

Traceback (most recent call last):
  File "drive_with_heading.py", line 11, in <module>
    sphero.power.wake()
  File "/usr/local/lib/python3.6/dist-packages/pysphero/device_api/power.py", line 76, in wake
    self.request(PowerCommand.wake)
  File "/usr/local/lib/python3.6/dist-packages/pysphero/device_api/device_api.py", line 30, in request
    timeout=timeout,
  File "/usr/local/lib/python3.6/dist-packages/pysphero/core.py", line 183, in request
    response = self._get_response(packet, timeout=timeout)
  File "/usr/local/lib/python3.6/dist-packages/pysphero/core.py", line 124, in _get_response
    raise PySpheroTimeoutError(f"Timeout error for response of {packet}")
pysphero.exceptions.PySpheroTimeoutError: Timeout error for response of Packet(flg: 0x0a did: 0x13 cid: 0x0d seq: 0x01)

**Comment by EnotYoyo** [comment]
Hello! 
See #2. 
In short, I don't know, how resolve this issues. May be, after #5, it will disappear. 
I tried to use a ping-packet, but it did not help.

**Comment by EnotYoyo** [comment]
I want to rewrite this library from bluepy  to another bluetooth library. Maybe gatt-python or bleak.  
I hope, that all such errors go away after that.

**Comment by EnotYoyo** [comment]
Added support for python-gatt.
